swagger: "2.0"

info:
  title: "Liquid Handling Robot"
  description: "Pecorino API"
  version: "1.0.0"

host: "localhost:3000"
basePath: "/api"
schemes:
  - http

paths:
  /motors/enabled:
    x-swagger-router-controller: motorsController
    put:
      operationId: enableMotors
      produces:
        - application/json
      responses:
        200:
          description: "Success"

    delete:
      operationId: disableMotors
      produces:
        - application/json
      responses:
        200:
          description: "Success"
    
  /port:
    x-swagger-router-controller: portController
    get:
      operationId: getPort
      produces:
        - application/json
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Port"

    post:
      operationId: setPort
      produces:
        - application/json
      parameters:
        - in: body
          name: port
          schema:
            $ref: "#/definitions/Port"

      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Port"
        
  /position:
    x-swagger-router-controller: positionController
    get:
      operationId: getPosition
      produces:
        - application/json
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Position"

    post:
      operationId: moveToPosition
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: position
          schema:
            $ref: "#/definitions/Position"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Position"
       
  /position/home:
    x-swagger-router-controller: positionController
    get:
      operationId: getHomeStatus
      produces:
        - application/json
      responses:
        200:
          description: "Success"

    post:
      operationId: goHome
      produces:
        - application/json
      responses:
        200:
          description: "Success"

  /position/reset:
    x-swagger-router-controller: positionController
    post:
      operationId: resetPosition
      produces:
        - application/json
      responses:
        200:
          description: "Success"

  /status/pins:
    x-swagger-router-controller: statusController
    get:
      operationId: getPinsStatus
      produces:
        - application/json
      responses:
        200:
          description: "Success"

  
  


definitions:
  Position:
    type: object
    required:
      - x
      - y
      - z
    properties:
      x:
        type: number
        format: float
      y:
        type: number
        format: float
      z:
        type: number
        format: float

  Port:
    type: object
    required:
      - name
    properties:
      name:
        type: string
    